import type { Metadata } from "next";
import "./globals.css";
import { GameProvider } from "@/context/gameContext";

export const metadata: Metadata = {
  title: "Text Dungeon Crawler",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GameProvider>
        <body>
          {children}
        </body>
      </GameProvider>
    </html>
  );
}
